apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-scale-app-rs
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scaler
              env:
                - name: SCALE_DEPLOYMENT
                  value: "my-app"
                - name: SCALE_REPLICAS
                  value: "2"
                - name: SCALE_DRY_RUN
                  value: "false"
                - name: RUST_LOG
                  value: "info"
