apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Optional component: include from an overlay to create the "deploy"
# ServiceAccount. Skip including it if the SA already exists in the
# target namespace.

resources:
  - serviceaccount.yaml
