apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-scale-app-rs
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scaler
              env:
                - name: K8S_SCALE_DEPLOYMENT
                  value: "my-app"
                - name: K8S_SCALE_REPLICAS
                  value: "1"
                - name: K8S_SCALE_DRY_RUN
                  value: "true"
                - name: RUST_LOG
                  value: "debug"
